# Generated by Django 5.2.4 on 2025-07-12 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IzipayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_code', models.CharField(help_text='Código de comercio proporcionado por Izipay', max_length=50, verbose_name='Código de comercio')),
                ('api_key', models.CharField(help_text='Clave API para autenticación con Izipay', max_length=255, verbose_name='Clave API')),
                ('hash_key', models.CharField(help_text='Clave Hash para validación de integridad', max_length=255, verbose_name='Clave Hash')),
                ('public_key', models.TextField(help_text='Clave pública RSA para encriptación', verbose_name='Clave Pública RSA')),
                ('script_url', models.URLField(default='https://sandbox-checkout.izipay.pe/payments/v1/js/index.js', help_text='URL del script JavaScript de Izipay', validators=[django.core.validators.URLValidator()], verbose_name='URL del Script Izipay')),
                ('is_sandbox', models.BooleanField(default=True, help_text='Activar para usar el entorno de pruebas', verbose_name='Modo Sandbox')),
                ('is_active', models.BooleanField(default=True, help_text='Marcar como configuración activa para usar', verbose_name='Configuración Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Configuración Izipay',
                'verbose_name_plural': 'Configuraciones Izipay',
                'ordering': ['-created_at'],
            },
        ),
    ]
