# Generated by Django 5.2.4 on 2025-07-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(help_text="The name of the Shopify store (e.g., 'your-store.myshopify.com').", max_length=255, unique=True)),
                ('api_key', models.CharField(help_text='The API key for your Shopify custom app.', max_length=255)),
                ('api_secret', models.CharField(help_text='The API secret key for your Shopify custom app.', max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='Is this the currently active configuration?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shopify Configuration',
                'verbose_name_plural': 'Shopify Configurations',
            },
        ),
    ]
