# Generated by Django 5.2.4 on 2025-07-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyconfig',
            name='access_token',
            field=models.CharField(blank=True, help_text='The Admin API access token for your Shopify app.', max_length=255),
        ),
        migrations.AlterField(
            model_name='shopifyconfig',
            name='api_key',
            field=models.CharField(blank=True, help_text='The API key for your Shopify custom app (legacy).', max_length=255),
        ),
        migrations.AlterField(
            model_name='shopifyconfig',
            name='api_secret',
            field=models.CharField(blank=True, help_text='The API secret key for your Shopify custom app (legacy).', max_length=255),
        ),
    ]
